# Generated by Django 4.1.3 on 2022-12-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fontes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fonte', models.CharField(max_length=250)),
            ],
        ),
    ]
