# Generated by Django 4.1.3 on 2022-12-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscavadorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
